### ISSUE TITLE
hacktoberfest-accepted" label

### ISSUE THREAD

**Issue by devrapture** [emmalearnscode/basic-calculator#3]
Pls, can you pls make this repo eligible for hacktoberfest by adding a hacktoberfest label? Thanks. I hope the feature I added is cool.

**Comment by EmmaDawsonDev** [comment]
Hello! I've added the hacktoberfest-accepted label to it instead of adding the whole repo (as I don't want lots of changes made to this file). This should work according to the new rules. I'm really busy with school this week so I'll look at your code properly at the weekend so I can understand how you put everything together and then hopefully merge it.
